In [135]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [9]:
%cd /content/drive/My Drive/sih

/content/drive/My Drive/sih


In [0]:
!python bin.py

In [0]:
from keras.models import model_from_json
from sklearn.externals import joblib
from collections import deque
class Trajectory:
    def __init__(self,modelPath='architecture.json',weightsPath='weights.h5',scalerPath = "scaler.pkl"):
        '''
            modelPath to be like = 'architecture.json'
            weightsPath to be like = 'weights.h5'
        '''
        json_file = open(modelPath, 'r')
        loaded_model_json = json_file.read()
        json_file.close()
        self.model = model_from_json(loaded_model_json)
        self.model.load_weights(weightsPath)
        self._look_back = 5
        self.scaler = joblib.load(scalerPath)
    def predictValues(self,x,lenPred=1):
        '''
        x is the small sequence
        shape should be (no. of rows,5,3)
        -1,3
        Look back is fixed to be 5 and
        3 is the params in each sequence
        lenPred Should be how many further points you want
        '''
        pred = []
        x = np.array(x)
        x = self.scaler.transform(x)
        x.reshape(-1,5,3)    
        x = deque(x)
        assert(len(x) == self._look_back)
        for i in range(lenPred):
            # print("x before",np.array(x).shape)
            x_prime = self.model.predict(np.array(x).reshape((-1,self._look_back,3)))
            x.popleft()
            x.extend([x_prime])
            # print("X_prime",x_prime.shape)
            # print(x)
            # print("x after",np.array(x).shape)
            pred.append(x_prime)
        pred = np.array(pred)
        pred = pred.reshape((-1,3))
        pred = self.scaler.inverse_transform(pred)
        return pred
    def predict(self,x,lenPred):
      x = deque(x)
      pred = []
      for i in range(lenPred):
        xTemp = self.predictValues(x)
        x.popleft()
        x.extend(xTemp)
        pred.append(xTemp)
      return pred

In [0]:
import numpy as np
traj = Trajectory(modelPath="architecture.json",weightsPath="weights.h5",scalerPath = "scaler.pkl")
x = [[[-13954, -9455, 27],[-13925, -9255, 71],[-14265, -9055, 117],[-14615, -8853, 163],[-14974, -8651, 207]]]
x = np.array(x).reshape(-1,3)
# print(x)
val = traj.predict(x,20)

In [131]:
val

[array([[-14296.621  ,  -9506.418  ,    196.83185]], dtype=float32),
 array([[-14199.755  ,  -9312.509  ,    198.79486]], dtype=float32),
 array([[-14553.936 ,  -9748.091 ,    171.5743]], dtype=float32),
 array([[-14491.606  , -10615.035  ,    170.97166]], dtype=float32),
 array([[-13830.373  , -10270.684  ,    152.50987]], dtype=float32),
 array([[-13715.824  , -10962.191  ,    121.97435]], dtype=float32),
 array([[-13532.627   , -11077.52    ,    106.676384]], dtype=float32),
 array([[-12484.53   , -11192.959  ,     98.42277]], dtype=float32),
 array([[-12565.705   , -11806.853   ,     54.724503]], dtype=float32),
 array([[-11765.46   , -11755.1045 ,     52.69295]], dtype=float32),
 array([[-11056.038   , -12106.635   ,     32.272995]], dtype=float32),
 array([[-1.1209219e+04, -1.2687429e+04, -1.1162033e+01]], dtype=float32),
 array([[-9.8296514e+03, -1.2520855e+04,  5.7912645e+00]], dtype=float32),
 array([[ -9776.98    , -13116.609   ,    -45.489048]], dtype=float32),
 array([[ -94

In [132]:
val

[array([[-14296.621  ,  -9506.418  ,    196.83185]], dtype=float32),
 array([[-14199.755  ,  -9312.509  ,    198.79486]], dtype=float32),
 array([[-14553.936 ,  -9748.091 ,    171.5743]], dtype=float32),
 array([[-14491.606  , -10615.035  ,    170.97166]], dtype=float32),
 array([[-13830.373  , -10270.684  ,    152.50987]], dtype=float32),
 array([[-13715.824  , -10962.191  ,    121.97435]], dtype=float32),
 array([[-13532.627   , -11077.52    ,    106.676384]], dtype=float32),
 array([[-12484.53   , -11192.959  ,     98.42277]], dtype=float32),
 array([[-12565.705   , -11806.853   ,     54.724503]], dtype=float32),
 array([[-11765.46   , -11755.1045 ,     52.69295]], dtype=float32),
 array([[-11056.038   , -12106.635   ,     32.272995]], dtype=float32),
 array([[-1.1209219e+04, -1.2687429e+04, -1.1162033e+01]], dtype=float32),
 array([[-9.8296514e+03, -1.2520855e+04,  5.7912645e+00]], dtype=float32),
 array([[ -9776.98    , -13116.609   ,    -45.489048]], dtype=float32),
 array([[ -94

In [0]:
lfrom math import *
import math

In [73]:
#Let Missile Location Coordinates
traj_x = -16494
traj_y = -7800
traj_z = 200

#Let prediction Location Coordinates
traj1_x =-16387.025
traj1_y = -9707.095
traj1_z = 80.613

#let Actual Cordinates of Air Object
traj_currx = -14974
traj_curry = -8651
traj_currz = 207

#Let Velocity of Target Shooting Missile

initial_velocity = 410

distance_x = traj_x - traj1_x
distance_y = traj_y - traj1_y
distance_z = traj_x - traj1_z

theta = math.atan(distance_x / distance_y)
phi = math.atan(distance_z / distance_x)

#Let Acceleration Due To Gravity is
g = 9.8

#Time needed by Object to move at predicted Position

Time_needed = 5

#if (Time_needed_to reach predicted point == Time Needed by MIssile to hit the object) therfore we can shoot at that point of time.

Distance = sqrt((traj1_x - traj_x)**2 + (traj1_y - traj_y)**2 + (traj1_z - traj_z)**2)
print(Distance) 
print(initial_velocity * math.cos(theta)*math.sin(phi)*Time_needed - (0.5*g*((Time_needed)**2)))
if abs(Distance - (initial_velocity * math.cos(theta)*math.sin(phi)*Time_needed - (0.5*g*((Time_needed)**2)))) <= 15:
    print("We can shoot")
else:
    print("Wait For the Next Interception")
    print(initial_velocity * math.cos(theta)*math.sin(phi)*Time_needed - (0.5*g*((Time_needed)**2)))


1913.8203273606948
1924.2398571596063
We can shoot
